-- local Element = require("TV.apps.sand.Element")
-- local components = require("TV.apps.sand.components")
-- local ElementManager = require("TV.apps.sand.ElementManager")

-- local element = Element:new()
-- element.id = "everything"
-- element.colour = vec(1, 0, 1, 1)
-- element.acid_immune = true
-- element.gas = true
-- element.fluid = true
-- element.liquid = true
-- element.components = {
--     components.acid,
--     components.fluid,
--     components.gas,
--     components.gravity,
--     components.cold,
--     -- components.condense,
--     components.evaporate,
--     components.group_gravity,
--     components.heat,
--     components.rise,
--     components.sink,
--     components.slide,
--     components.spread,
--     components.thermite,
--     components.wet,
-- }
-- element.transitions = {
--     heat = function(self) self.element = ElementManager:get("everything") end,
--     condense = function(self) self.element = ElementManager:get("everything") end,
--     wet = function(self) self.element = ElementManager:get("everything") end,
-- }

-- return element
